# -*- coding: utf-8 -*-
"""E-Commerce Sales .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dCZvF-Bu1gdtDJga6b3NrLWp_g1eX50h

# 🐼 Pandas Backup Class — E-Commerce Sales & Customer Analytics

Welcome! This notebook is built for **practice, not memorization**.

**Dataset:** `ecommerce_sales_data.csv` — a realistic (but intentionally messy)
e-commerce dataset with customers, orders, and business metrics.

> 💡 Tip: This dataset was created ON PURPOSE with missing values, duplicates,
> wrong data types, inconsistent text, and outliers — because real company
> data always looks like this. Cleaning it is part of the lesson!

## 1. Reading the Dataset — `read_csv`
"""

import pandas as pd
import numpy as np

data = pd.read_csv("ecommerce_sales_data.csv")
data

"""
## 2. First Look at the Data — `head`, `tail`, `sample`

"""

data.head()

data.tail()

data.sample()

"""## 3. Understanding the Structure — `shape`, `columns`, `dtypes`, `info`, `describe`"""

data.shape

data.columns

data.dtypes

data.info()

data.describe()

"""## 4. Selecting Data — Indexing, `loc`, `iloc`"""

data['Customer_Name']

data.loc[0:4, ['Customer_Name', 'City', 'Total_Amount']]

data.iloc[0:4, 0:6]

"""## 5. Filtering Data (Boolean Conditions)"""

data
data.info()
delivered = data[data['Order_Status'] == 'Delivered']
delivered

# Multiple conditions: Gold members from Delhi with rating >= 4
mask = (data['Membership_Type'] == 'Gold') & (data['City'] == 'Delhi') & (data['Rating'] >= 4)
data[mask]

"""## 6. Sorting Data — `sort_values`"""

data.sort_values(by='Total_Amount', ascending=False)

"""## 7. Exploring Categories — `value_counts`, `unique`, `nunique`"""

# How many orders per Product_Category
print(data['Product_Category'].value_counts())

# List of unique payment methods
print("\nPayment methods:", data['Payment_Method'].unique())

# Unique cities in the dataset
print("\nUnique cities:", data['City'].nunique())

"""## 8. Handling Missing Values — `isnull`, `fillna`, `dropna`"""

data.isnull().sum()

data

# Fill numeric missing values with the column median
data['Age'] = data['Age'].fillna(data['Age'].median())
print(data['Age'])
data['Rating'] = data['Rating'].fillna(data['Rating'].median())
print(data['Rating'])
data['Discount'] = data['Discount'].fillna(data['Discount'].median())
print(data['Discount'])
data['Total_Amount'] = data['Total_Amount'].fillna(data['Total_Amount'].median())
print(data['Total_Amount'])


# Fill categorical missing values with a placeholder
data['City'] = data['City'].fillna('Unknown')
print(data['City'])
data['Customer_Satisfaction'] = data['Customer_Satisfaction'].fillna('Not Provided')
print(data['Customer_Satisfaction'])

data[['Age', 'Rating', 'Discount','Total_Amount', 'City', 'Customer_Satisfaction']].isnull().sum()

# dropna() example: drop rows still missing critical values (e.g. Delivery_Date, Profit)
# (shown here without overwriting df, just to see the effect)
cleaned_subset = data.dropna(subset=['Delivery_Date', 'Profit'])
print("Rows before dropna:", data.shape[0])
print("Rows after dropna on Delivery_Date & Profit:", cleaned_subset.shape[0])

"""## 9. Duplicate Handling"""

print(data.duplicated().sum())   #rows

# Dup_orderID = data[data.duplicated(subset='Order_ID', keep=False)]    # keep=False -> jitni bhi dup_order ids hai sabko True mark karta hai
# print(Dup_orderID.shape[0])   # no. of dup_orderid = 231
# Dup_orderID
# Dup_orderID.sort_values(by='Order_ID')

data = data.drop_duplicates(subset='Order_ID', keep='first')
print(data['Order_ID'].duplicated().sum())
data.shape

"""## 10. `groupby`, `agg`, and `transform`"""

# Average Total_Amount per Product_Category
avg_amount = data.groupby('Product_Category')['Total_Amount'].mean()
avg_amount.sort_values(ascending=False)

# agg(): multiple aggregations at once, grouped by Region
data.groupby('Region').agg(
    Total_Revenue=('Revenue', 'sum'),
    Avg_Order_Value=('Total_Amount', 'mean'),
    Orders=('Order_ID', 'count')
).sort_values('Total_Revenue', ascending=False)

data['Category_Avg_Amount'] = data.groupby('Product_Category')['Total_Amount'].transform('mean')
data[['Product_Category', 'Total_Amount', 'Category_Avg_Amount']]

"""## 11. Data Type Fixing (`astype`)"""

data.dtypes

# Clean 'Gender' -> strip spaces, standardize case
data['Gender'] = data['Gender'].str.strip().str.upper()
data['Gender'] = data['Gender'].replace({'MALE': 'Male', 'FEMALE': 'Female', 'M': 'Male', 'F': 'Female'})
print(data['Gender'].unique())

# Clean 'Unit_Price' -> remove commas, then convert to float
data['Unit_Price'] = data['Unit_Price'].astype(str).str.replace(',', '', regex=False).astype(float)

# Clean 'Profit' -> remove currency symbol (₹), then convert to float
data['Profit'] = data['Profit'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False)
data['Profit'] = pd.to_numeric(data['Profit'], errors='coerce')

# Fix Age -> whole numbers make more sense than floats
data['Age'] = data['Age'].astype(int)

data[['Unit_Price', 'Profit', 'Age']].dtypes

data['Order_Date'] = pd.to_datetime(data['Order_Date'], errors='coerce', format='mixed', dayfirst=False)
data['Delivery_Date'] = pd.to_datetime(data['Delivery_Date'], errors='coerce', format='mixed', dayfirst=False)

data[['Order_Date', 'Delivery_Date']].dtypes

data.info()